操作 | 说明 
---|---
a.ndim | 数组的秩
a.size | 元素的总个数
a.shape | 形状，行列维度
a.dtype | 元素类型

## 一维数组
- 和python数组不一样，只能是同一类型

In [3]:
import numpy as np
np.__version__

'1.13.3'

In [9]:
a = np.arange(0, 10)
b = np.arange(10)
c = np.arange(0,10,2)
print(a, b, c)

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9] [0 2 4 6 8]


In [4]:
a = np.array([0,1,2,3])
b = np.array([[1,3,5], [2,4,8]])

In [5]:
print(a)
print(b)
print(type(a))
print(a[::-1])

[0 1 2 3]
[[1 3 5]
 [2 4 8]]
<class 'numpy.ndarray'>
[3 2 1 0]


In [ ]:
print(a.ndim)
print(a.size) # n dimensional array n维数组
print(a.shape)

In [ ]:
print(b.ndim)
print(b.size)
print(b.shape)
print(b)

## 特殊矩阵
功能 | 创建 | 举例
--- | --- |---:
全0矩阵 | np.zeros((2,3)) | a=np.zeros((2,3))<br>[[ 0.  0.  0.]<br>[ 0.  0.  0.]]
全1矩阵 | np.ones((3,3)) | --
单位矩阵 | np.eye(2) | 2阶单位矩阵
对角矩阵，k为对角线的偏移 | np.diag([1,2,3],k=0)| --

In [15]:
print(np.zeros((2,3)))
print('-'*25)
print(np.ones((3,3)))
print('-'*25)
print(np.eye(2))
print('-'*25)
print(np.diag([1,2,3],k=0))


[[ 0.  0.  0.]
 [ 0.  0.  0.]]
-------------------------
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]
-------------------------
[[ 1.  0.]
 [ 0.  1.]]
-------------------------
[[1 0 0]
 [0 2 0]
 [0 0 3]]


## 中间数、平均值
1. 中间数np.median(a)
2. 平均值np.mean(a)
#### 若是矩阵，不指定axis默认求所有元素的均值
1. axis=0，求列的均值
2. axis=1，求行的均值