操作 | 说明 
---|---
a.ndim | 数组的秩
a.size | 元素的总个数
a.shape | 形状，行列维度
a.dtype | 元素类型

## 一维数组
> 和python数组不一样，只能是同一类型

In [2]:
import numpy as np
np.__version__

'1.13.3'

In [9]:
a = np.arange(0, 10)
b = np.arange(10)
c = np.arange(0,10,2)
print(a, b, c)

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9] [0 2 4 6 8]


In [4]:
a = np.array([0,1,2,3])
b = np.array([[1,3,5], [2,4,8]])

In [5]:
print(a)
print(b)
print(type(a))
print(a[::-1])

[0 1 2 3]
[[1 3 5]
 [2 4 8]]
<class 'numpy.ndarray'>
[3 2 1 0]


In [ ]:
print(a.ndim)
print(a.size) # n dimensional array n维数组
print(a.shape)

In [ ]:
print(b.ndim)
print(b.size)
print(b.shape)
print(b)

## 特殊矩阵
功能 | 创建 | 举例
--- | --- |---:
全0矩阵 | np.zeros((2,3)) | a=np.zeros((2,3))<br>[[ 0.  0.  0.]<br>[ 0.  0.  0.]]
全1矩阵 | np.ones((3,3)) | --
单位矩阵 | np.eye(2) | 2阶单位矩阵
对角矩阵，k为对角线的偏移 | np.diag([1,2,3],k=0)| --

In [7]:
np.zeros(9)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [5]:
np.zeros(9).dtype

dtype('float64')

In [6]:
np.zeros(9, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [11]:
np.zeros(shape=(3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [13]:
np.ones((3,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [20]:
# 指定值矩阵
np.full((3,5), 77)

array([[77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77]])

In [41]:
# 起点 终点 步长
# 步长不能为 浮点数
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [38]:
# 步长 可为 浮点数
np.arange(0, 20, 2.5)

array([  0. ,   2.5,   5. ,   7.5,  10. ,  12.5,  15. ,  17.5])

In [18]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [19]:
print(np.diag([1,2,3],k=0))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


### linspace 等差数列

In [47]:
# 起点 终点 等长截出n个数
np.linspace(1, 20 , 10)

array([  1.        ,   3.11111111,   5.22222222,   7.33333333,
         9.44444444,  11.55555556,  13.66666667,  15.77777778,
        17.88888889,  20.        ])

In [49]:
# 包括起点 和 终点
np.linspace(1, 20 , 11)

array([  1. ,   2.9,   4.8,   6.7,   8.6,  10.5,  12.4,  14.3,  16.2,
        18.1,  20. ])

### 生成随机数

In [53]:
np.random.randint(0, 10)

8

In [51]:
np.random.randint(0, 10, 5)

array([5, 1, 1, 2, 4])

## 中间数、平均值
1. 中间数np.median(a)
2. 平均值np.mean(a)
#### 若是矩阵，不指定axis默认求所有元素的均值
1. axis=0，求列的均值
2. axis=1，求行的均值