操作 | 说明 
---|---
a.ndim | 几维数组
a.size | 元素的总个数
a.shape | 形状，行列维度
a.dtype | 元素类型

## 一维数组
> 和python数组不一样，只能是同一类型

In [2]:
import numpy as np
np.__version__

'1.13.3'

In [9]:
a = np.arange(0, 10)
b = np.arange(10)
c = np.arange(0,10,2)
print(a, b, c)

[0 1 2 3 4 5 6 7 8 9] [0 1 2 3 4 5 6 7 8 9] [0 2 4 6 8]


In [30]:
# 将一维数组转化为 二维数组
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
X[2,3]

13

#### 数组切片
用元祖，单括号

In [31]:
# 前2行， 前3列
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [32]:
# 前2行， 前3列
X[:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [33]:
X[:, :3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [36]:
# 前2行 间隔为2；切片表达式放在不同的维度中
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [38]:
# 矩阵反转
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [41]:
X[0, :]

array([0, 1, 2, 3, 4])

In [44]:
X[:, 1].ndim

1

In [48]:
# 子矩阵，会影响原矩阵
# 和Python list 不同，优先考虑效率
subX = X[:2, :3]
subX[0, 0] = 111
X

array([[111,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [50]:
subX = X[:2, :3].copy()
subX[0, 0] = 112
X

array([[111,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

### reshape
修改维度

In [59]:
x = np.arange(10)
x.shape

(10,)

In [63]:
# -1 自定计算元素个数
x.reshape(2, -1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [55]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a = np.array([0,1,2,3])
b = np.array([[1,3,5], [2,4,8]])

In [5]:
print(a)
print(b)
print(type(a))
print(a[::-1])

[0 1 2 3]
[[1 3 5]
 [2 4 8]]
<class 'numpy.ndarray'>
[3 2 1 0]


In [ ]:
print(a.ndim)
print(a.size) # n dimensional array n维数组
print(a.shape)

In [ ]:
print(b.ndim)
print(b.size)
print(b.shape)
print(b)

## 特殊矩阵
功能 | 创建 | 举例
--- | --- |---:
全0矩阵 | np.zeros((2,3)) | a=np.zeros((2,3))<br>[[ 0.  0.  0.]<br>[ 0.  0.  0.]]
全1矩阵 | np.ones((3,3)) | --
单位矩阵 | np.eye(2) | 2阶单位矩阵
对角矩阵，k为对角线的偏移 | np.diag([1,2,3],k=0)| --

In [7]:
np.zeros(9)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [5]:
np.zeros(9).dtype

dtype('float64')

In [6]:
np.zeros(9, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
np.zeros((3,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [11]:
np.zeros(shape=(3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [13]:
np.ones((3,5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [20]:
# 指定值矩阵
np.full((3,5), 77)

array([[77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77],
       [77, 77, 77, 77, 77]])

In [41]:
# 起点 终点 步长
# 步长不能为 浮点数
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [38]:
# 步长 可为 浮点数
np.arange(0, 20, 2.5)

array([  0. ,   2.5,   5. ,   7.5,  10. ,  12.5,  15. ,  17.5])

In [18]:
np.eye(2)

array([[ 1.,  0.],
       [ 0.,  1.]])

In [19]:
print(np.diag([1,2,3],k=0))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


### linspace 等差数列

In [47]:
# 起点 终点 等长截出n个数
np.linspace(1, 20 , 10)

array([  1.        ,   3.11111111,   5.22222222,   7.33333333,
         9.44444444,  11.55555556,  13.66666667,  15.77777778,
        17.88888889,  20.        ])

In [49]:
# 包括起点 和 终点
np.linspace(1, 20 , 11)

array([  1. ,   2.9,   4.8,   6.7,   8.6,  10.5,  12.4,  14.3,  16.2,
        18.1,  20. ])

### 生成随机数

In [53]:
np.random.randint(0, 10)

8

In [51]:
np.random.randint(0, 10, 5)

array([5, 1, 1, 2, 4])

In [3]:
np.random.randint(0, 10, size=(3, 5))

array([[8, 6, 9, 6, 3],
       [4, 7, 5, 1, 2],
       [7, 0, 3, 1, 6]])

In [4]:
# 随机种子， 2次生成一致数组
# np.random.seed(666)

In [7]:
np.random.random(7)

array([ 0.07934213,  0.48678052,  0.1536739 ,  0.82846513,  0.19136857,
        0.27040895,  0.56103442])

In [10]:
# 0~1 之间
np.random.random((3,5))

array([[ 0.90238039,  0.85178834,  0.41808196,  0.39347627,  0.01622051],
       [ 0.29921337,  0.35377822,  0.89350267,  0.78613657,  0.77138693],
       [ 0.42005486,  0.77602514,  0.46430814,  0.18177017,  0.8840256 ]])

In [11]:
# 服从正态分布
np.random.normal()

0.9459234072350854

In [18]:
# 均值为10， 方差为100
np.random.normal(10, 100)

-176.8855480878589

In [19]:
np.random.normal(0, 1, size=(3, 5))

array([[ 0.10037737, -3.09487059,  3.39351678, -0.12666878, -0.93713026],
       [ 0.56552529,  0.3158975 , -0.79572225,  0.50507572,  0.32482413],
       [ 0.9608153 ,  0.03026866,  0.57605275, -0.06992037,  0.64549479]])

In [25]:
# 查询文档
np.random.normal?

In [23]:
# 嵌入book内
# help(np.random.normal)

## 中间数、平均值
1. 中间数np.median(a)
2. 平均值np.mean(a)
#### 若是矩阵，不指定axis默认求所有元素的均值
1. axis=0，求列的均值
2. axis=1，求行的均值