# 使用scikit-learn中的kNN
[1.6. Nearest Neighbors — scikit-learn 0.20.2 documentation](https://scikit-learn.org/stable/modules/neighbors.html)

kNN不需要训练过程，没有模型的算法

训练数据集`本身`就是模型

Count投票处理

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
raw_data_X = [[3.393533211, 2.331273381],
              [3.110073483, 1.781539638],
              [1.343808831, 3.368360954],
              [3.582294042, 4.679179110],
              [2.280362439, 2.866990263],
              [7.423436942, 4.696522875],
              [5.745051997, 3.533989803],
              [9.172168622, 2.511101045],
              [7.792783481, 3.424088941],
              [7.939820817, 0.791637231]
             ]
raw_data_y = [0, 0, 0, 0, 0, 1, 1, 1, 1, 1]

X_train = np.array(raw_data_X)
y_train = np.array(raw_data_y)

x = np.array([8.093607318, 3.365731514])

### 魔法命令调用 .py文件

In [3]:
%run kNN_classify.py

In [4]:
predict_y = kNN_classify(6, X_train, y_train, x)

In [5]:
predict_y

1

<br><br><br>

## 使用scikit-learn中的kNN

`fit  →  predict`

In [6]:
from sklearn.neighbors import KNeighborsClassifier

In [7]:
# 创建实例
kNN_classifier = KNeighborsClassifier(n_neighbors=6)

In [8]:
kNN_classifier.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=6, p=2,
           weights='uniform')

### kNN_classifier.predict(x)

ValueError: Expected 2D array, got 1D array instead:
array=[ 8.09360732  3.36573151].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

为了统一接口，都传二维数组

#### 解决方案一

In [20]:
x

array([ 8.09360732,  3.36573151])

In [12]:
# 新版sklearn，所有数据都应该是二维矩阵
# 哪怕只有单独1行或1列（比如前面做预测时，仅仅只用了一个样本数据）所以需要使用.reshape(1,-1)进行转换，具体操作如下。
kNN_classifier.predict([x])

array([1])

#### 解决方案二

In [21]:
# 第1个维度是1，第二个维度由sk自由决定
X_predict = x.reshape(1, -1)

In [14]:
X_predict

array([[ 8.09360732,  3.36573151]])

In [17]:
kNN_classifier.predict(X_predict)

array([1])

In [18]:
y_predict = kNN_classifier.predict(X_predict)

In [19]:
y_predict[0]

1

<br><br><br>

## 重新整理我们的kNN的代码

In [ ]:
knn_clf = KNNClassifier(3)

In [ ]:
knn_clf.fit(X_train, y_train)

In [ ]:
y_predict = knn_clf.predict(X_predict)

In [ ]:
y_predict

In [ ]:
y_predict[0]