# Scikit-Learn制作训练 / 测试数据

In [1]:
import numpy as np
import pandas as pd
from sklearn import datasets

In [2]:
iris=datasets.load_iris()

In [3]:
X = iris.data
y = iris.target

In [4]:
X.shape

(150, 4)

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## 拆分数据集
~~将前100个作训练集，后面做测试集？？~~

❎数据集是排好序的！

原始数据，先`shuffle`洗牌，乱序再处理

X | y 又是分开的？？如何统一

In [6]:
# 索引的随机排列
shuffle_indexes = np.random.permutation(len(X))
shuffle_indexes

array([ 76,  25,  85,  74,  28,  58,  32,  52,  94,  18, 107, 132, 142,
       144, 145,   7, 129,  24,  78,   2, 139,  99,  86,  88, 117,  84,
        82,  54,  83,  47,  64,  67,  69, 130,  70, 141,  98, 119,  40,
        12, 112,  42, 143,  95,  66,  27,  30,  56, 126,  13,  48,  59,
       122, 146,  23, 116, 123,  35,  11,  51,   6,  20,  62,  71, 101,
        38, 124,  89,   4, 115,   0,  68,  36, 106,  21,  65,  97,  57,
       131,  79,  45,  17,   1,  37, 135,  26, 100,  55, 137,  14,  29,
        10,  91,  15, 125,  19, 110, 102,  93,  41,  81, 128,   9, 105,
        61, 113, 120,  53,  22, 134, 104, 111, 103,  92,  50,  96, 133,
        49,  87,  46, 138,  33,  31,  73, 121,  63,  60,  90,  44, 149,
        16, 136,   3,  72,   5, 108,  77,   8, 114,  80, 109,  34, 118,
       140, 147,  75, 127, 148,  39,  43])

In [7]:
test_ratio = 0.2
train_size = int(len(X) * (1 - test_ratio))

In [8]:
train_indexes = shuffle_indexes[:train_size]
test_indexes = shuffle_indexes[train_size:]

In [10]:
test_indexes.size

30

In [11]:
X_train = X[train_indexes]
y_train = y[train_indexes]

X_test = X[test_indexes]
y_test = y[test_indexes]

In [12]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [13]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


<br><br>

## 自己制作Python模块

并预测

In [2]:
from playML.model_selection import train_test_split

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [6]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)


In [7]:
print(X_test.shape)
print(y_test.shape)

(30, 4)
(30,)


In [9]:
from playML.kNN import KNNClassifier

In [17]:
my_knn_clf = KNNClassifier(k=3)

In [26]:
my_knn_clf.fit(X_train, y_train)

KNN(k=3)

In [27]:
y_predict = my_knn_clf.predict(X_test)

In [28]:
y_predict

array([1, 2, 2, 0, 1, 2, 1, 1, 1, 0, 2, 2, 0, 0, 1, 1, 1, 1, 1, 0, 2, 1, 2,
       1, 2, 0, 0, 1, 0, 0])

In [31]:
sum(y_predict==y_test)

28

In [32]:
sum(y_predict==y_test) / len(y_test)

0.93333333333333335

<br><br>

## sklearn中封装的切分数据集方法

In [33]:
from sklearn.model_selection import train_test_split

train_test_split 带有随机数性质

想复现之前的拆分，传1个随机种子：`random_state=666`

后续实验可重复

In [36]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=666)

In [37]:
print(X_train.shape)
print(y_train.shape)

(120, 4)
(120,)
