## 协方差计算

In [18]:
import numpy as np
np.random.randState = 123
x = np.random.randint(10, start =1, size=12)
y = np.random.randint(10, size=12)

In [31]:
print(x)
print(y)

[1 0 9 9 6 1 5 0 0 6 5 4]
[0 5 6 3 3 2 2 5 8 9 7 0]


In [22]:
print(np.mean(x), np.var(x), np.std(x))
print(np.mean(y), np.var(y), np.std(y))

3.8333333333333335 10.472222222222221 3.2360813064912666
4.166666666666667 8.138888888888888 2.852873794770615


In [30]:
np.cov(x, y)

array([[11.42424242,  0.75757576],
       [ 0.75757576,  8.87878788]])

In [33]:
x_ex = x-np.mean(x)

In [35]:
y_ex = y - np.mean(y)

In [36]:
xy = x_ex * y_ex

In [37]:
np.mean(xy)

0.6944444444444445

In [38]:
np.cov(x, y)

array([[11.42424242,  0.75757576],
       [ 0.75757576,  8.87878788]])

In [67]:
x.var()

10.472222222222221

In [39]:
import pandas as pd

In [41]:
df_x = pd.DataFrame(x)
df_y = pd.DataFrame(y)

In [48]:
df_y.cov()

0
0  8.878788

In [51]:
df_x.var()

0    11.424242
dtype: float64

In [53]:
df_y.var()

0    8.878788
dtype: float64

In [58]:
df = pd.DataFrame({
    "a":[1, 0, 9, 9, 6, 1, 5, 0, 0, 6, 5, 4],
    "b":[0, 5, 6, 3, 3, 2, 2, 5, 8, 9, 7, 0,]
})

In [61]:
df["a"].corr(df["b"])

0.07522038005569737

In [66]:
df["a"].cov(df["b"])

0.7575757575757573

In [62]:
df.corr()

a        b
a  1.00000  0.07522
b  0.07522  1.00000

In [63]:
df.cov()

a         b
a  11.424242  0.757576
b   0.757576  8.878788

In [64]:
df["a"].var()

11.424242424242424

In [65]:
df["b"].var()

8.878787878787877