操作 | 说明 
---|---
a.ndim | 数组的秩
a.size | 元素的总个数
a.shape | 形状，行列维度

## 一维数组

In [3]:
import numpy as np
a = np.array([0,1,2,3])
b = np.array([[1,3,5], [2,4,8]])

In [10]:
print(a)
print(type(a))
print(a[::-1])

[0 1 2 3]
<class 'numpy.ndarray'>
[3 2 1 0]


In [5]:
print(a.ndim)
print(a.size) # n dimensional array n维数组
print(a.shape)

1
4
(4,)


In [9]:
print(b.ndim)
print(b.size)
print(b.shape)
print(b)

2
6
(2, 3)
[[1 3 5]
 [2 4 8]]
[[2 4 8]]


## 特殊矩阵
功能 | 创建 | 举例
--- | --- |---:
全0矩阵 |  np.zeros() | a=np.zeros((2,3))<br>[[ 0.  0.  0.]<br>[ 0.  0.  0.]]
