### 聚合操作
- 统计相关

In [2]:
import numpy as np

In [6]:
L = np.random.random(100)

In [7]:
# 直接用sum(L) 效率差些
np.sum(L)

52.476215502148342

In [8]:
np.max(L)

0.9936704742685426

In [10]:
np.max(L)

0.9936704742685426

In [9]:
np.min(L)

0.015124277234282557

#### 理解记忆
- 0 是行；1 是列
- 沿着某个维度，把它压缩到一起，再进行操作

In [13]:
A = np.arange(16).reshape(4,-1)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [14]:
np.sum(A)

120

In [15]:
# 沿着某一维进行计算
np.sum(A, axis=0)

array([24, 28, 32, 36])

In [16]:
np.sum(A, axis=1)

array([ 6, 22, 38, 54])

In [17]:
# 所有元素乘积
np.prod(A)

0

In [18]:
np.prod(A+1)

20922789888000

In [19]:
# 均值
np.mean(A)

7.5

In [21]:
# 中位数
np.median(A)

7.5

In [23]:
v = np.array([1,2,2,2,10])
np.mean(v)

3.3999999999999999

In [24]:
np.median(v)

2.0

In [26]:
# 百分位点
for percent in [0, 25, 50, 75, 100]:
    print(np.percentile(A, q=percent)) # 百分位

0.0
3.75
7.5
11.25
15.0


In [27]:
# 方差
np.var(A)

21.25

In [28]:
np.std(A)

4.6097722286464435

In [30]:
# 正态分布
X = np.random.normal(0, 1, size=1000000)

In [31]:
np.mean(X)

-0.0013539146242044593

In [32]:
np.std(X)

1.0001265132561847

### 索引
- arg运算

In [33]:
np.min(X)

-4.8548477618493067

In [34]:
# 最小数的索引
np.argmin(X)

680079

In [35]:
X[680079]

-4.8548477618493067

### 排序和使用索引

In [39]:
x = np.arange(16)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [41]:
# 乱序处理，洗牌
np.random.shuffle(x)
x

array([ 8, 14, 11,  5,  9, 12,  6,  2,  3,  1, 13,  0,  7, 15, 10,  4])

In [42]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [43]:
x

array([ 8, 14, 11,  5,  9, 12,  6,  2,  3,  1, 13,  0,  7, 15, 10,  4])

In [45]:
# 区别
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [57]:
np.random.shuffle(x)
x

array([ 5,  2,  9,  4, 15, 10, 12,  7,  8, 13, 11,  3, 14,  1,  6,  0])

In [58]:
# 索引数组 排序
np.argsort(x)

array([15, 13,  1, 11,  3,  0, 14,  7,  8,  2,  5, 10,  6,  9, 12,  4])

In [59]:
# 标定点
np.partition(x, 5)
# 5 前面的数都比它小，但不是有序的
# 5 后面的数都比它大，也不是有序的
# 切片处理

array([ 2,  0,  1,  4,  3,  5, 12, 10,  8, 13, 11, 15, 14,  9,  6,  7])

#### 二维数组排序

In [47]:
B = np.random.randint(10, size=(4,4))
B

array([[9, 5, 1, 8],
       [7, 5, 5, 1],
       [4, 9, 5, 8],
       [2, 3, 5, 3]])

In [48]:
np.sort(B)

array([[1, 5, 8, 9],
       [1, 5, 5, 7],
       [4, 5, 8, 9],
       [2, 3, 3, 5]])

In [50]:
np.sort(B, axis=0)

array([[2, 3, 1, 1],
       [4, 5, 5, 3],
       [7, 5, 5, 8],
       [9, 9, 5, 8]])

#### 填数组，找没有规律的数据点

### numpy.array 比较

In [64]:
x.sort()
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [63]:
x > 3

array([False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [65]:
x != 3

array([ True,  True,  True, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True], dtype=bool)

In [68]:
2 * x == 24 - 4*x

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False], dtype=bool)

In [70]:
np.sum(x <= 3)

4

In [79]:
np.sum(x%2 == 0)

8

In [77]:
np.count_nonzero(x <= 3)

4

存在 - 都满足

In [72]:
# 有没元素等于 0 
np.any(x == 0)

True

In [75]:
# 所有元素 都大于 0吗
np.all(x > 0)

False

In [76]:
np.all(x >= 0)

True

In [80]:
# 位运算符
# 年龄大于3，小于10的小朋友
np.sum((x>3) & (x<10))

6

In [81]:
np.sum((x>3) && (x<10))

SyntaxError: invalid syntax (<ipython-input-81-5dd5d89911d0>, line 1)

In [82]:
# 位运算符
# 年龄不等于0 的小朋友
np.sum(~(x==0))

15

### 抽出具体数据
- 专业用pandas，做数据预处理

In [83]:
# 年龄小于5的小朋友，是谁
x[x<5]

array([0, 1, 2, 3, 4])

In [84]:
x[x%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])